### ISSUE TITLE
BitGlad Proposal

### ISSUE THREAD

**Issue by BitGlad1** [bitsongofficial/delegation-program#1]
## Type of Proposal

- [x] Feature Request (e.g. functionality)

- [x] Economic Model

- [ ] Underlying Technology (e.g. performance)

- [ ] Application Development

- [ ] Marketing/Community Building

- [ ] Communication Channels

- [ ] Documentation

- [ ] Others

## Background

 test1

## Describe The Proposal (No more than 50 words)
Test1

 Test Saro 1

## Business Model (Optional for underlying technology) Test Saro 2

 Test Saro 2

## Implementation Steps (Optional for economic model)

 Test Saretto

## Expected Outcome
Big time Saro

 Test

## Additional Context (Optional)

 None

## Contact Information 

sfasfasgasgas

 saro@gmail.com

## For Admin Use

- [ ] Not duplicate proposal
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
