### ISSUE TITLE
ITA Stakers Proposal

### ISSUE THREAD

**Issue by itastakers-devs** [bitsongofficial/delegation-program#13]
## Type of Proposal

- [ ] Feature Request (e.g. functionality)

- [ ] Economic Model

- [ ] Underlying Technology (e.g. performance)

- [x] Application Development

- [ ] Marketing/Community Building

- [x] Communication Channels

- [ ] Documentation

- [ ] Others

## Background

We are the first Italian Bitsong validator that follows the project from the beginning.
We are also active as validators and contributors in other projects of the Cosmos ecosystem. We develop tools and useful content for communities to spread knowledge about the blockchain.

## Describe The Proposal 

Fan Token Dashboard
We want to develop a dashboard for the community that allows you to monitor the publication of new fan tokens on Bitsong and how to obtain them.
New listings, information on fan tokens and much more will be available.

## Implementation Steps 

We will launch a dedicated node to constantly monitor the chain and events dedicated to Fan Tokens. The node will need to be active and maintained for all the time necessary for development and, most likely, even after to give full resources to the tool.
We will release a free version of the dashboard that will allow the monitoring of new listings and access to Fan Token info.
We will talk about Bitsong Fan Tokens through our social networks, through the ITAStakers community and through the other Cosmos projects we collaborate with.

## Expected Outcome

Making Bitsong and the new Fan Tokens more accessible and better known

## Contact Information

itastakers@gmail.com

## For Admin Use

- [x] Not duplicate proposal
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
