### ISSUE TITLE
Rundax Proposal

### ISSUE THREAD

**Issue by Hantok** [bitsongofficial/delegation-program#14]
## Type of Proposal

- [+] Feature Request (e.g. functionality)

- [ ] Economic Model

- [ ] Underlying Technology (e.g. performance)

- [ ] Application Development

- [ ] Marketing/Community Building

- [+] Communication Channels

- [+] Documentation

- [+] Others

## Background

Rundax is an experienced team of Software engineers from Ukraine. We are the first Ukrainian validator since the first testnet. Besides Bitsong, we run validators in Solana and Minter blockchains. Also, we have about 10 years of experience in software development:
- Big Data
- Blockchains (Bitcoin and Ethereum based) dev
- Web dev
- Mobile dev

## Describe The Proposal (No more than 50 words)

- Add handy Docker setup for Bitsong node
- Add handy Kubernetes support for Bitsong to be able to run a node in few clicks in Kubernetes clusters
- Adopt node monitoring systems for Bitsong node - full open-source access
- Keep Russian speaking community up to date, help with tutorials and translations
- Provide public node API per request 

## Implementation Steps (Optional for economic model)

We already adopted Tendermint based node to be easily run in Docker. We implement node-runner for the Kubernetes cluster as well. We require up to 2 weeks to do the same for Bitsong. All is free and open-source.

## Expected Outcome

Provide easy steps to run Bitsong nodes with few clicks on almost any platform for anyone with basic node monitoring tools

## Contact Information

roman@rundax.com
Telegram: Hantok

## For Admin Use

- [+] Not duplicate proposal
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
