### ISSUE TITLE
action bot - ANAMIX

### ISSUE THREAD

**Issue by dbpatty** [bitsongofficial/delegation-program#15]
## Type of Proposal

- [ ] Feature Request (e.g. functionality)

- [ ] Economic Model

- [ ] Underlying Technology (e.g. performance)

- [ ] Application Development

- [ ] Marketing/Community Building

- [ ] Communication Channels

- [ ] Documentation

- [X ] Others

## Background
Anamix is a team that has been passionate about the crypto world since the end of 2015, we believe that kind of tools can help validators and community.

## Describe The Proposal (No more than 50 words)

We would create a telegram bot that warns about new releases.

## Implementation Steps (Optional for economic model)

In a first phase our bot warns about new projects release, it'll follow the Github version and content.
With the evolution of the project we would add a scheduled message with this info (for i.e.):
BTSG PRICE $ 0.07
MARKET CAP $ 7 931 703
LATEST BLOCK 797204
TOTAL TXS -
VALIDATORS 61/62
BONDED RATIO 29.21 %
VOTING POWER 30 991 470.079582 BTSG
INFLATION 8.16 %
TOTAL SUPPLY 106 089 157.692972 BTSG
COMMUNITY POOL 15 022 352.445893 BTS

## Contact Information

dbpatty.dev@gmail.com

## For Admin Use

- [ ] Not duplicate proposal
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
