### ISSUE TITLE
StakeLab proposal

### ISSUE THREAD

**Issue by zdeadex** [bitsongofficial/delegation-program#6]
## Type of Proposal

- [x] Marketing/Community Building

- [x] Communication Channels

- [x] Documentation

- [x] Others

## Background

StakeLab is the first validator for french speakers. We develop a platform to initiate non crypto users to the defi and to dpos long term investment. We are securing 8m $ assets on 9 networks. Mid term development would be to add all langages to have one platform for long term invest for all countries.
We are validating on Bitsong since early mainnet (since we did hear about) and really like the idea.

## Describe The Proposal (No more than 50 words)

We plan to create tutorials, tips, uses of the tools, and community building in french (then others langages).
Also helping on Ledger app/Live as Ledger employee (contact, helps...)

## Business Model (Optional for underlying technology)

"One" Click delegating for "expert users". Initiation and advice for novice/intermediaire users.
StakeLab is the only platform helping on your first steps into the defi investments.

## Implementation Steps (Optional for economic model)

First step will be to integrate delegation tutorials to make the users safely stake their btsg.
Second step is to provide "how to use" stuff for people to make them understanding the bitsong platform and tools.
At the time of all of this, we will build the french community and help users in needs.

## Expected Outcome

More users, more security for users (less security issue) and more attractivity on the project.

## Contact Information

partenariat@stakelab.fr

## For Admin Use

- [ ] Not duplicate proposal
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
