### ISSUE TITLE
cyberG Proposal

### ISSUE THREAD

**Issue by Vgk88** [bitsongofficial/delegation-program#9]
## Type of Proposal

- [ ] Feature Request (e.g. functionality)

- [ ] Economic Model

- [ ] Underlying Technology (e.g. performance)

- [ ] Application Development

- [x] Marketing/Community Building

- [x] Communication Channels

- [x] Documentation

- [x] Others

## Background

I am Vadym. Bitsong validator from Ukraine. Validating since testnet 3. I am part of Distributed Validators Synctems. 

## Describe The Proposal (No more than 50 words)

I want to help Bitsong developing Russian and Ukrainian community. I can help with documentation translation and community building. I want to attract new artist and users to the Bitsong Platform.

## Business Model (Optional for underlying technology)

Creating guides and blog post about Bitsong. Creating airdrops for new user in Russian and Ukrainian community.

## Implementation Steps (Optional for economic model)

Finding active members of Russian and Ukrainian communities. Creating guides and tutorials about Bitsong. attracting new artists to Bitsong.

## Expected Outcome

Creating strong community for Bitsong

## Contact Information

88vgk88@gmail.com

## For Admin Use

- [ ] Not duplicate proposal
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by BitGlad1** [comment]
Hi there,

Thanks for your proposal.

Please fill in the Timetable too and explain a little bit more in detail which tools are you aiming to use to attracting artists and users to join the ecosystem and which kind of guides and tutorials are you looking forward to create.

Regards
